# Generated by Django 4.0.1 on 2022-01-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunch',
            name='category',
            field=models.CharField(default='Protein', max_length=48),
        ),
        migrations.AddField(
            model_name='lunch',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
